# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Fotios Fotis
title: Student of Ionian University at the Informatics Department
email: p16foti@ionio.gr
website: https://github.com/p16foti

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  p16foti
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: namedff
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: 56847974_2463241237033061_3986337989855805440_n.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Fotios and I'm a Student of Ionian University at the Informatics Department. Experienced in Programming Languages such as C, C++, Java. Attended courses on Network Security and Ethical Hacking. Worked on Information System Analysis and Design projects. Working on Software Εngineering and eager to develop my knowledge and skills in the field.

  I am most skilled in: <mark>C++</mark> and <mark>Java</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Awesome project
        link: github.com/p16foti
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
         # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project on Software Εngineering and eager to develop my knowledge and skills in the field. I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Informatics Department
        link: di.ionio.gr/
        # link_text: boringcompany.com
        sub_title: Student of Ionian University
        caption: October 2016 - Present
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Experienced in Programming Languages such as C, C++, Java and worked on Information System Analysis and Design projects.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ionian University
        caption: 2016 - Present
        sub_title: Informatics Department
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I am still attending courses and trying to develop my knowledge and skills in Informatics.

          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Playing football
      - Gaming
      - [Becoming a Beatmaker](https://www.youtube.com/watch?v=pDIsEZsalAo)

     

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
